### ISSUE TITLE
ImportError: No module named dylutils

### ISSUE THREAD

**Issue by ghost** [CSD-Public/stonix#1]
I have build deb package with ./deb_build_script.py  and installed it. I am getting following runtime error:

WARNING:OS:Ubuntu 14.04.2 LTS
WARNING:STONIXversion:0.8.17
WARNING:RunTime:2015-05-14 09:40:49
WARNING:PropertyNumber:0
WARNING:SystemSerialNo:0
WARNING:ChassisSerialNo:0
WARNING:SystemManufacturer:Unk
WARNING:ChassisManufacturer:Unk
WARNING:UUID:0
WARNING:PropertyNumber:0
ERROR:**main**:getrules:Error importing rule: Traceback (most recent call last):
  File "/usr/bin/stonix", line 332, in getrules
    mod = **import**(module)
  File "/usr/bin/stonix_resources/rules/DisableAutoLogin.py", line 45, in <module>
    from ..dylutils import *
ImportError: No module named dylutils
Traceback (most recent call last):
  File "/usr/bin/stonix", line 1223, in <module>
    STONIXAPP = Controller()
  File "/usr/bin/stonix", line 231, in **init**
    allrules = self.getrules(self.config, self.environ)
  File "/usr/bin/stonix", line 336, in getrules
    "Error importing rule: " + trace)
  File "/usr/bin/stonix_resources/logdispatcher.py", line 231, in log
    self.reporterr(msg, prefix)
  File "/usr/bin/stonix_resources/logdispatcher.py", line 271, in reporterr
    server = smtplib.SMTP(localize.MAILRELAYSERVER)
  File "/usr/lib/python2.7/smtplib.py", line 251, in **init**
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

**Comment by roynielsen17** [comment]
Should be fixed now.

**Comment by ghost** [comment]
Thanks. it is fine now.
